name: Advon Analytics
markdown: redcarpet
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title.html
url: https://www.advonanalytics.com
timezone: America/Chicago

include: [_redirects]

plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
