backend:
  name: github
  repo: zarekio/advon
  branch: master
  site_domain: advonanalytics.com
media_folder: "images/uploads"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Updated Date", name: "date", widget: "datetime"}
      - {label: "Published?", name: "published", widget: "boolean", default: "false"}
      - {label: "Comments", name: "comments", widget: "boolean", default: "true"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string", default: "JD"}
